### PR TITLE
Prepare for melpa

### LINKED ISSUE #3: Suggestion to add this to tempel repo readme or wiki
First of all, Thank you for making this package!

I thought without yasnippet, eglot wouldnt complete the snippets from lsp.

Someone from matrix, posted this, and voila, works like charm with tempel! Just as i wanted!

I was on the verge to open issue with eglot or either ask minad for the support.
And here you sir, have done the job!

## I recommend you to add about this package to corfu's and tempel's readme.
There could be someone who might encounter this issue, so..

## Add this package to **Melpa** (easy to discover)

Thank you!

### PR DESCRIPTION
**Pull request by fejfighter**
Minor Fixes from checkdoc, builds and package-lint as per melpa requirements.

Also set license as GPL3 to meet the same requirement, and will need @faerryn to agree for the changes made in #2 and #1. given it was previously without any license on the repository I am hoping there is minimal concern.

closes: #3

### CODE REVIEW

**Comment by fejfighter** [comment]
@faerryn wanted to bump this and hope that this change has just fallen off your radar rather than you having any particular opposition to it.

edit: I can't seem to assign you as a reviewer to make the process clearer/easier

**Comment by faerryn** [comment]
What should I do? Sorry, new to this.

**Comment by fejfighter** [comment]
No worries, I think there were a couple of issues with the PR

Not sure why github wouldn't let me add you as a reviewer before, but it does now.

if you're happy with your changes being GPL just hit approve, I'll sort the rest

**Review by faerryn — APPROVED** [review]
Horray!

**Pull request merged**
